# @package _global_
hydra:
  searchpath:
    - pkg://Heimdall  # Heimdall path

####
# Set the specific parameters you would like to change from the defaults
####
project_name: Cell_Type_Classification_dev  # project name for WandB
run_name: run_name  ## what is set for WandB
work_dir: work_dir  ## set your custom working directory
run_wandb: true
float_dtype: float32
data_path: /work/magroup/shared/Heimdall/data
ensembl_dir: ${data_path}
cache_preprocessed_dataset_dir:
overwrite: false
entity: Heimdall
only_preprocess_data: false
seed: 42

###
# Set the experiment parts you would like to import
####
defaults:
  - _self_  # NOTE: init self first
  - /scfm_config: default
