# @package _global_
defaults:
  - /scfm_config/tasks@scfm_config.tasks.default: pretrain_geneformer_dev
  - override /scfm_config/model@scfm_config.model: transformer_lmhead
  - override /scfm_config/dataset@scfm_config.dataset: pancreas
  - override /scfm_config/scheduler@scfm_config.scheduler: cosine
  - override /scfm_config/trainer@scfm_config.trainer: default
  - override /scfm_config/optimizer@scfm_config.optimizer: AdamW
  - override /scfm_config/fc@scfm_config.fc: geneformer
  - override /scfm_config/fg@scfm_config.fg: identity
  - override /scfm_config/loss@scfm_config.loss: CrossEntropyLoss

project_name: pancreas_pretrain_geneformer
run_name: '${scfm_config.model.type}_lr${scfm_config.optimizer.args.lr}_bz${scfm_config.tasks.default.args.batchsize} '

scfm_config:
  optimizer:
    args:
      lr: 2e-3

seed: 55
work_dir: work_dir
