# @package _global_
defaults:
  - /scfm/tasks@scfm.tasks.default: cell_type_annotation
  - override /scfm/model@scfm.model: transformer
  - override /scfm/dataset@scfm.dataset: pancreas
  - override /scfm/scheduler@scfm.scheduler: cosine
  - override /scfm/trainer@scfm.trainer: default
  - override /scfm/optimizer@scfm.optimizer: AdamW
  - override /scfm/fc@scfm.fc: geneformer
  - override /scfm/fe@scfm.fe: sorting
  - override /scfm/fg@scfm.fg: identity
  - override /scfm/loss@scfm.loss: CrossEntropyLoss

project_name: cell_type_classification_dev
run_name: test01

scfm:
  optimizer:
    args:
      lr: 2e-3
  tasks:
    default:
      args:
        epochs: 1
  trainer:
    accumulate_grad_batches: 1

seed: 55
work_dir: work_dir
