# @package _global_
defaults:
  - /scfm_config/tasks@scfm_config.tasks.default: spatial_cta_hard
  - override /scfm_config/model@scfm_config.model: expression_only
  - override /scfm_config/dataset@scfm_config.dataset: spatial_cta_hard
  - override /scfm_config/scheduler@scfm_config.scheduler: cosine
  - override /scfm_config/trainer@scfm_config.trainer: default
  - override /scfm_config/optimizer@scfm_config.optimizer: AdamW
  - override /scfm_config/fc@scfm_config.fc: dummy
  - override /scfm_config/fe@scfm_config.fe: dummy
  - override /scfm_config/fg@scfm_config.fg: dummy

project_name: spatial_cta_hard
run_name: ${scfm_config.fg.type}_${scfm_config.fe.type}_${scfm_config.fc.type}_${scfm_config.model.type}_lr${scfm_config.optimizer.args.lr}_bz${scfm_config.tasks.default.args.batchsize}

scfm_config:
  optimizer:
    args:
      lr: 2e-3
  tasks:
    default:
      args:
        dataset_config:
          type: Heimdall.datasets.SingleInstanceDataset
        head_config:
          args:
          type: Heimdall.models.ExpressionOnlyCellPredHead

seed: 55
work_dir: work_dir
